[package]
name = "fpm"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
directories = "6.0.0"
hyper = "1.6.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
